[package]
name = "img-mt"
version = "0.1.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
description = """
A tool to load huge images and do measurements on them
"""
repository = "https://github.com/wose/img-mt"
license = "MIT"
exclude = ["docs", ".travis.yml"]

[dependencies]
